export type Paper = {
  id: string
  subject: string
  course: string
  semester: number
  year: number
  session: "Winter" | "Summer"
  uploadedAt: string
  status: "pending" | "approved" | "rejected"
  uploadedBy: string
}

export const courses = [
  "B.Sc. Computer Science",
  "B.Sc. Information Technology",
  "B.Com",
  "B.A.",
  "B.E. Computer Engineering",
  "B.E. Electronics",
  "B.E. Mechanical",
  "BMS",
  "BAF",
  "BBI",
]

export const semesters = [1, 2, 3, 4, 5, 6, 7, 8]

export const subjects: Record<string, string[]> = {
  "B.Sc. Computer Science": [
    "Data Structures",
    "Operating Systems",
    "Database Management",
    "Computer Networks",
    "Software Engineering",
    "Web Technologies",
    "Discrete Mathematics",
    "Python Programming",
  ],
  "B.Sc. Information Technology": [
    "Data Structures",
    "Operating Systems",
    "Database Management",
    "Network Security",
    "Cloud Computing",
    "Mobile Computing",
    "Software Testing",
    "AI & Machine Learning",
  ],
  "B.Com": [
    "Financial Accounting",
    "Business Economics",
    "Business Law",
    "Cost Accounting",
    "Taxation",
    "Auditing",
    "Management Accounting",
    "Commerce",
  ],
  "B.A.": [
    "English Literature",
    "History",
    "Political Science",
    "Sociology",
    "Psychology",
    "Economics",
    "Philosophy",
    "Geography",
  ],
  "B.E. Computer Engineering": [
    "Data Structures & Algorithms",
    "Operating Systems",
    "Database Management Systems",
    "Computer Networks",
    "Machine Learning",
    "Software Engineering",
    "Compiler Design",
    "Distributed Computing",
  ],
  "B.E. Electronics": [
    "Digital Electronics",
    "Analog Circuits",
    "Signal Processing",
    "Control Systems",
    "VLSI Design",
    "Microprocessors",
    "Communication Systems",
    "Embedded Systems",
  ],
  "B.E. Mechanical": [
    "Thermodynamics",
    "Fluid Mechanics",
    "Machine Design",
    "Manufacturing Processes",
    "Heat Transfer",
    "Automobile Engineering",
    "CAD/CAM",
    "Robotics",
  ],
  "BMS": [
    "Business Communication",
    "Principles of Management",
    "Financial Management",
    "Marketing Management",
    "Human Resource Management",
    "Strategic Management",
    "Business Ethics",
    "Operations Research",
  ],
  "BAF": [
    "Financial Accounting",
    "Cost Accounting",
    "Taxation",
    "Auditing",
    "Financial Management",
    "Management Accounting",
    "Business Law",
    "Economics",
  ],
  "BBI": [
    "Banking Operations",
    "Insurance Operations",
    "Financial Markets",
    "Risk Management",
    "International Banking",
    "Financial Services",
    "Business Law",
    "Economics",
  ],
}

export const mockPapers: Paper[] = [
  {
    id: "1",
    subject: "Data Structures",
    course: "B.Sc. Computer Science",
    semester: 3,
    year: 2024,
    session: "Winter",
    uploadedAt: "2025-01-15",
    status: "approved",
    uploadedBy: "Rahul S.",
  },
  {
    id: "2",
    subject: "Operating Systems",
    course: "B.Sc. Computer Science",
    semester: 4,
    year: 2024,
    session: "Summer",
    uploadedAt: "2025-01-12",
    status: "approved",
    uploadedBy: "Priya M.",
  },
  {
    id: "3",
    subject: "Database Management",
    course: "B.Sc. Information Technology",
    semester: 3,
    year: 2024,
    session: "Winter",
    uploadedAt: "2025-01-10",
    status: "approved",
    uploadedBy: "Amit K.",
  },
  {
    id: "4",
    subject: "Financial Accounting",
    course: "B.Com",
    semester: 1,
    year: 2024,
    session: "Winter",
    uploadedAt: "2025-01-08",
    status: "approved",
    uploadedBy: "Sneha R.",
  },
  {
    id: "5",
    subject: "Computer Networks",
    course: "B.E. Computer Engineering",
    semester: 5,
    year: 2023,
    session: "Winter",
    uploadedAt: "2024-12-20",
    status: "approved",
    uploadedBy: "Vikram J.",
  },
  {
    id: "6",
    subject: "Business Economics",
    course: "B.Com",
    semester: 2,
    year: 2024,
    session: "Summer",
    uploadedAt: "2024-12-18",
    status: "approved",
    uploadedBy: "Neha P.",
  },
  {
    id: "7",
    subject: "Python Programming",
    course: "B.Sc. Computer Science",
    semester: 2,
    year: 2024,
    session: "Summer",
    uploadedAt: "2024-12-15",
    status: "approved",
    uploadedBy: "Rohan D.",
  },
  {
    id: "8",
    subject: "Digital Electronics",
    course: "B.E. Electronics",
    semester: 3,
    year: 2023,
    session: "Winter",
    uploadedAt: "2024-12-10",
    status: "approved",
    uploadedBy: "Kavita S.",
  },
  {
    id: "9",
    subject: "Thermodynamics",
    course: "B.E. Mechanical",
    semester: 3,
    year: 2024,
    session: "Winter",
    uploadedAt: "2025-01-20",
    status: "pending",
    uploadedBy: "Suresh M.",
  },
  {
    id: "10",
    subject: "Machine Learning",
    course: "B.E. Computer Engineering",
    semester: 7,
    year: 2024,
    session: "Winter",
    uploadedAt: "2025-01-22",
    status: "pending",
    uploadedBy: "Ananya T.",
  },
  {
    id: "11",
    subject: "Cloud Computing",
    course: "B.Sc. Information Technology",
    semester: 5,
    year: 2024,
    session: "Summer",
    uploadedAt: "2025-01-18",
    status: "pending",
    uploadedBy: "Deepak R.",
  },
  {
    id: "12",
    subject: "Marketing Management",
    course: "BMS",
    semester: 4,
    year: 2024,
    session: "Summer",
    uploadedAt: "2025-01-25",
    status: "pending",
    uploadedBy: "Meera K.",
  },
  {
    id: "13",
    subject: "Software Engineering",
    course: "B.Sc. Computer Science",
    semester: 5,
    year: 2023,
    session: "Summer",
    uploadedAt: "2024-11-05",
    status: "approved",
    uploadedBy: "Arjun N.",
  },
  {
    id: "14",
    subject: "Web Technologies",
    course: "B.Sc. Computer Science",
    semester: 4,
    year: 2023,
    session: "Winter",
    uploadedAt: "2024-10-28",
    status: "approved",
    uploadedBy: "Pooja V.",
  },
]
